version: '3'
services:
  dbs:
    hostname: retoapp_dbs
    image: mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPASS}
    volumes:
      - retoapp-dbs-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    hostname: retoapp_web
    build: .
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - dbs

volumes:
  retoapp-dbs-data: {}
