# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host:     <%= ENV['DBHOST'] || localhost %>
  username: <%= ENV['DBUSER'] || "root" %>
  password: <%= ENV['DBPASS'] || "" %>

production:
  <<: *default
  database: <%= ENV['DBNAME'] %>

development:
  <<: *default
  database: <%= ENV['DBNAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DBNAME_TEST'] %>
